name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_fonts: ^4.0.4
  provider: ^6.1.2
  shared_preferences: ^2.0.8
  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  intl: ^0.19.0
  firebase_database: ^10.4.10
  firebase_storage: ^11.6.10
  camera: ^0.10.5+9
  gallery_saver: '^2.3.2'
  http: ^0.13.3
  http_parser: ^4.0.0
  just_audio: ^0.9.36
  flutter_sound: ^8.4.0
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.2
  path: ^1.9.0
  video_player: ^2.8.3
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  location: ^5.0.0
  flutter_polyline_points: ^1.0.0
  geocoding: ^3.0.0
  speech_to_text: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/recognize.png
    - assets/convlog.webp
    - assets/geofence.jpg
    - assets/user.webp
    - assets/signup.png
    - assets/signout.png
    - assets/newuser.png
    - assets/convlog.png
    - assets/recognize(2).png
    

android:
  package: com.example.flutter_application_1



